### ISSUE TITLE
Failure Reason: No such file or directory

### ISSUE THREAD

**Issue by BruceZCQ** [danielebogo/DBCamera#145] opened 2015-03-13 03:20 UTC
use pod , when I running the app show below error
```
/Users/BruceZCQ/Projects/PaiYiPai/paiyipai/Pods/GPUImage/framework/Resources/lookup_miss_etikate.png
/Users/BruceZCQ/Projects/PaiYiPai/paiyipai/Pods/GPUImage/framework/Resources/lookup_soft_elegance_1.png
/Users/BruceZCQ/Projects/PaiYiPai/paiyipai/Pods/GPUImage/framework/Resources/lookup_soft_elegance_2.png
building file list ... done

sent 615 bytes  received 20 bytes  1270.00 bytes/sec
total size is 378223  speedup is 595.63
/* com.apple.actool.notices */
/Users/BruceZCQ/Projects/PaiYiPai/paiyipai/DBCamera/DBCamera/Resources/DBCameraImages.xcassets: warning: Failed to read file attributes for "/Users/BruceZCQ/Projects/PaiYiPai/paiyipai/DBCamera/DBCamera/Resources/DBCameraImages.xcassets"
    Failure Reason: No such file or directory
/* com.apple.actool.compilation-results */

Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure
```

**Comment by danielebogo** [comment] 2015-03-13 15:20
Hi @BruceZCQ ,
did you launch pod install and use the xcworkspace instead of xcodeproj?

**Comment by filipandrei87** [comment] 2015-03-15 16:25
This happens to me as well. Using pod install. Latest Xcode version (6.2)

**Comment by BruceZCQ** [comment] 2015-03-16 03:03
@danielebogo  use the xcworkspace

**Comment by danielebogo** [comment] 2015-03-16 10:07
Hi guys,
can you tell me the iOS deployment target and the device/simulator you use to build/run the app?

**Comment by filipandrei87** [comment] 2015-03-16 10:28
iOS 8 deployment target. Error appears on both simulator and iPhone 6 device.
As far as I can tell, it related to the script that is run to include the DBCamera assets in the project. (the default graphics don't appear).

This error does not stop the project from running. As far as I can tell, it only fails to load the assets. I've copied them into the project as well to make sure they appear.

**Comment by danielebogo** [comment] 2015-03-16 12:03
OK, thanks. I need to investigate because i've created a new project with only DBCamera as pod, but the build didn't show the error.

**Comment by mohitdream4u** [comment] 2015-03-16 12:41
Get same error with

/* com.apple.actool.notices */
.../../.../DBCamera/DBCamera/Resources/DBCameraImages.xcassets"
    Failure Reason: No such file or directory
/* com.apple.actool.compilation-results */

**Comment by danielebogo** [comment] 2015-03-16 12:57
I've generate a new tag and new version of DBCamera, changing a line in my DBCamera.podspec. You can see this file in my master repo. Can you use this podfile instead of the cocoapods path?

**Comment by danielebogo** [comment] 2015-03-16 13:00
Like this:
pod "DBCamera",          :podspec => "DBCamera.podspec" #this is my podspec. Save it in the same folder of Podfile

**Comment by farhanpatel** [comment] 2015-03-16 15:57
+1 Also seeing the same issue

**Comment by danielebogo** [comment] 2015-03-16 16:15
Ok, cocoapods has accepted the new version. Can someone test it?

**Comment by farhanpatel** [comment] 2015-03-16 16:22
Not working for me. I can point my pod directly to the git repo so you dont need to wait for cocoa pods to accept

**Comment by danielebogo** [comment] 2015-03-16 16:32
Take a look. It seems a Cocoapods problem: https://github.com/CocoaPods/CocoaPods/issues/3251

**Comment by gantulgats** [comment] 2015-03-18 06:40
i found a solution. Just downgrade i cooapods
open terminal
sudo gem uninstall cocoapods
sudo gem install cocoapods --version 0.35

**Comment by lekksi** [comment] 2015-03-18 06:49
Downgrading works probably because there seems to be a bug in one cocoapods script. If the problem is the same I had, it can be temporarily fixed by modifying the following shell script:

    Pods/Targets Support Files/Pods-*target-name*/Pods-*target-name*-resources.sh

    FROM: XCASSET_FILES="$XCASSET_FILES '$1'"
    TO:   XCASSET_FILES="$XCASSET_FILES '${PODS_ROOT}/$1'"

The problem is that the path given as argument for XCASSET_FILES hasn't been prefixed with ${PODS_ROOT} and thus searches for the assets in wrong path.

**Comment by cytryn** [comment] 2015-03-30 16:07
+1

**Comment by shams-ahmed** [comment] 2015-03-30 16:23
using the newest cocoapods 0.36.1 fixed the problem

**Comment by cytryn** [comment] 2015-03-30 16:28
Just installed 0.36.1 and it fixed for me also.

**Closed** 2015-03-31 10:21 UTC

**Comment by dasmer** [comment] 2015-04-15 02:55
Is this fixed? Still seeing this issue on 0.36.3

**Comment by danielebogo** [comment] 2015-04-18 11:47
Me either. I've done a downgrade to 0.35.

**Comment by dasmer** [comment] 2015-04-18 12:24
0.36.4 was just released and fixes this issue 🍻
